<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\fav_icon.ico</ApplicationIcon>
    <Version>4.1.0</Version>
    <AssemblyTitle>CS2 Server Picker</AssemblyTitle>
    <Description>Counter-Strike 2 Server Region Picker</Description>
    <Company>FN-FAL113</Company>
    <Product>CS2 Server Picker</Product>
    <Copyright>GNU General Public License V3</Copyright>
  </PropertyGroup>

  <PropertyGroup>
    <PublishSingleFile>false</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>false</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="WPF-UI" Version="3.0.5" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\fav_icon.ico" />
    <Resource Include="Assets\Flags\**\*.png" />
    <Resource Include="Assets\GitHub-Mark.png" />
    <Resource Include="Assets\Paypal.png" />
    <Resource Include="Assets\Settings.png" />
  </ItemGroup>

</Project>
